# Site settings
title: Nimish Kapoor
description: Nimish Kapoor's CV
favicon: /assets/img/avatar.png
baseurl: https://nimishkapoor.github.io/
url: https://nimishkapoor.github.io/
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Nimish Kapoor
  title: Software Engineering
  address: Bangalore, India
  email: nmshkpr#gmail.com
  link: https://drive.google.com/file/d/1DN8qKmCOmf0smSymrzmCi7FfUly0vqsU/view?usp=sharing
  weibo:
  github: nimishkapoor
  linkedin: nimish-kapoor-939741128/
  twitter: 
  gavatar: /resumecard/assets/img/avatar.png
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: Arista Networks
      location: Bangalore, India
      title: Application Development Engineer
      started: 2020
      duration: July 2020 - Present
      description: Full stack web development, machine learning and computer networking. Golang, Python, Flask, React, AWS, GCP, PHP, Salesforce, Redis, Kubernetes, Maria SQL and Postgres SQL.
    - work2:
      company: Arista Networks
      location: Bangalore, India
      title: Application Development Engineer Intern
      started: 2020
      duration: Jan 2020 - June 2014
      description: Developed an api which predicts case status by sentiment analysis of client emails for TAC team using machine learning models and is embedded into the QView, the main application used by TAC for handling all client issues. Developed two tools one to convert old EOS commands to new and vice versa. And other to configure the lab's device under testing automatically by using clients configuration file and modifying them according to lab's environment. For both these tools backend was completed in python, frontend in React JS and were deployed using Google cloud platform.
    - work3:
      company: Google Summer of Code at Scilab
      location: Paris, France (Remote)
      title: Intern Software Developer
      started: 2018
      duration: April 2018 - September 2018
      description: The aim of my project was to improve the code quality of Scilab with the help of various Static Analysis Tools​ like ​Scan Coverity(Java and C/C++), FindBugs(Java),​​ Cppcheck, Valgrind(Dynamic Analysis Tool for cross-checking Memory related fixes) and Clang-Tidy (last three for C/C++) by fixing Java, JNI and C/C++ ​ related errors​. In this project, I fixed various bugs, errors, defects, typical programming errors like style violations, interface misuse reported by Static analysis tools and provided comments to avoid future conflicts (e.g use of proper API). Hence, improved the overall quality of the Scilab code.
  educationHistory:
    - education1:
      organization: Amrita School Of Engineering
      location: Amritapuri, India
      degree: Bachelor
      major: Computer Science and Engineering
      started: 2016
      duration: (2016 - 2020)
      description: Passed with Distinction. Apart from the regular courses which were part of BTech Computer Science curriculum my electives in the college were Advance Algorithms, Computational Intelligence, Cryptography, Data Science, Pattern Recognition , Machine Learning and Data Mining, Intelligent Systems, Net Centric Programming, Pattern Recognition.
  languages:
    - language1:
      name: Hindi
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: Punjabi
      proficiency: Native
  programmingSkills:
    - skill1:
      name: C++
      percentage: 80%
    - skill2:
      name: Python
      percentage: 80%
    - skill3:
      name: Java
      percentage: 70%
    - skill4:
      name: JavaScript
      percentage: 60%
    - skill5:
      name: GOLang
      percentage: 70%
